### ISSUE TITLE
webrtc bridge?

### ISSUE THREAD

**Issue by jl777** [feross/webtorrent-hybrid#18]
Is it possible to setup a node as a bridge between webrtc and the normal internet torrent nodes? If so, then webrtc nodes that connect through these bridges would have access to the full torrent space.

Alternatively, TCP or UDP packets can be delivered to and from JS via pnacl. I am interested in creating a pure client side standalone app that connects to the tcp/udp torrent nodes.

https://github.com/jl777/SuperNET builds both native and chrome app versions of bitcoin node (still in development) which uses p2p over tcp connections.

Since webtorrent has the latest UI (as compared to webtorrent-chrome) and also connects to the full set  of torrent peers, I think bridging the two or just directly supporting normal peers in the chrome version would be possible. 

Ideally there would be a way to get the latest webtorrent to work as a chrome app, but not sure how best to achieve that

James

**Comment by Stiveknx** [comment]
About making a chrome extension, was talked before in:
[``](https://github.com/feross/webtorrent/issues/443)

**Comment by feross** [comment]
> Is it possible to setup a node as a bridge between webrtc and the normal internet torrent nodes?

That is certainly possible, but it's not the goal of `webtorrent-hybrid`. The goal of this package is to offer a "hybrid client".

Hybrid clients are just peers than can speak normal bittorrent (tcp) as well as webtorrent (webrtc). They can connect to both types of peers when they're downloading/seeding. They don't retransmit anything or act as a proxy. But when they become seeders, they can seed to both types of peers, of course.

A proxy doesn't make much sense because it would be expensive to run such a proxy, it wouldn't be P2P anymore, and it might result in the proxy downloading copyrighted content against it's will.

**Comment by feross** [comment]
Supporting normal peers in the chrome version is certainly an option. Right now, my focus is on building a desktop client: https://github.com/feross/webtorrent-app If you're interested in contributing, that's the place to do it, at the moment.
