### ISSUE TITLE
Investigate using electron-spawn instead of wrtc

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-hybrid#5]
Perhaps using the WebRTC implementation in [Electron](http://electron.atom.io/), via something like https://github.com/maxogden/electron-spawn would solve the problems with `wrtc`:

- memory usage
- segfaults
- no windows support

**Comment by Guiiks** [comment]
Hello,

First, thanks for this good job ;)

Maybe that's the reason why I have this error sometimes when running it with require('child_process').spawn no ?

WebTorrent(1402,0x7fff754bc300) malloc: *** error for object 0x100bcc780: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

Thanks,
Guillaume

**Comment by feross** [comment]
@Guiiks Yeah, this is the segfault that wrtc keeps causing.

**Comment by kevinsimper** [comment]
How would you go an implement this?

You spawn a electron process that would then communicate with webtorrent-hybrid by `ipc`?

**Comment by feross** [comment]
@kevinsimper 

> How would you go an implement this?

I was thinking you could have `simple-peer` expose it's API in node and then use async IPC to actually create the connection in the electron process. Use IPC for events and to keep the state of the Peer object in node in sync with the connection in electron.

> A quick solution right now would just to be seeding and leeching on both networks.

I don't see how this solves the segfault. The only way to fix that is to fix `wrtc`, or stop using it.

**Comment by zoudf** [comment]
I still can not build webtorrent-hybrid on RP2 since wrtc [ issue213 ](https://github.com/js-platform/node-webrtc/issues/213). 
hope electron-spawn can works well on RP2.

**Comment by Chocobozzz** [comment]
Unfortunately `webtorrent-hybrid` is not usable in production since `wrtc` is not stable and consums 100% of the CPU after a little moment. Moreover it doesn't seem actively maintened.

I tried your solution @feross but by putting `webtorrent` in an `electron-spawn` process and emulate methods that I need with `node-ipc`: https://github.com/Chocobozzz/PeerTube/blob/master/src/webTorrentNode.js for the node module and https://github.com/Chocobozzz/PeerTube/blob/master/src/webtorrent.js for webtorrent inside an electron process.

The result is the node process consums much less CPU (electron power), is faster and more reliable. I recommend this type of solution if you don't need advanced features of webtorrent.

Another option: there is another NodeJS module which can make WebRTC: https://github.com/js-platform/node-webrtc (I haven't try it with webtorrent-hybrid).

**Comment by feross** [comment]
@Chocobozzz Actually that other node module you linked to (https://github.com/js-platform/node-webrtc) is actually the same as `wrtc`.

Glad to hear that the `electron-spawn` approach works well. Perhaps we can make that the default going forward and support it well.

**Comment by Chocobozzz** [comment]
Oup's sorry this was the wrong link. I wanted to talk about https://github.com/vmolsa/webrtc-native

**Comment by olalonde** [comment]
Thanks @Chocobozzz, I will try this approach as well and report back.

**Comment by skeskinen** [comment]
I'm not having as much luck with electron-spawn as @Chocobozzz. Yea it kinda works, but it also uses a ton of CPU% after some uptime and just doesn't work for larger files. (maybe it's the same as this https://news.ycombinator.com/item?id=9690653 so it's probably workable limitiation ) I also get some (harmless?) error messages from chromium code that don't help to boost the confidence in this setup.

Based on my experience alone I would say that fixing wrtc seems to be the most promising approach even with it's own problems. But I really want to have this working so I'll keep testing.

**Comment by feross** [comment]
Another possible approach:

https://github.com/h2non/webtorrent-hybrid-electron
https://github.com/mappum/electron-webrtc

**Comment by feross** [comment]
Also: 

https://github.com/nickdesaulniers/node-rtc-peer-connection

**Comment by jobevers** [comment]
Two other options, but would require a bunch of work:

https://github.com/priologic/easyrtc/ - they claim to have a nodejs server running webrtc

https://github.com/EricssonResearch/openwebrtc - " The bulk of the API layer is implemented in JavaScript" but I have no idea how difficult it would be to integrate with node.

**Comment by jdoig** [comment]
There's seemingly no issue tracker on the webtorrent-hybrid-electron repo so I'll leave this here.

https://github.com/h2non/webtorrent-hybrid-electron
seems broken due to a dependancy on webtorrent 0.x but it requires 'webtorrent/bin/cmd' which isn't present after webtorrent version 0.84.1.

I'm no js dev so I can't put a PR in... But I did fix this locally by changing the package.json to pin webtorrent at 0.84.1

**Comment by rom1504** [comment]
@jdoig see https://github.com/h2non/webtorrent-hybrid-electron/pull/1 anyway

**Comment by Autarc** [comment]
@jdoig @rom1504 Since there were no updates at the fork and the bug you mentioned got fixed in newer version of [electron-webrtc](https://github.com/mappum/electron-webrtc), I've submitted the changes. Although it takes longer through the abstractions it works quite good with the existing implementations.

**Comment by feross** [comment]
`webtorrent-hybrid` is now based on `electron-webrtc` thanks to the work by @Autarc. This is released as v1.0.0.
