### ISSUE TITLE
convert magnet url to torrent file?

### ISSUE THREAD

**Issue by Mookambika** [feross/webtorrent-hybrid#59]
Hi, 

Is it possible in webtorrent-hybrid to convert magnet url to torrent file?

**Comment by feross** [comment]
You can't convert a straight magnet uri to a torrent file since the torrent file contains extra information (the piece hashes). But you can add it the node.js client, wait for the needed metadata to be retrieved from remote peers, and then access the torrent file with `torrent.torrentFile`. More info in the docs: https://webtorrent.io/docs

**Comment by Mookambika** [comment]
I have installed webtorrent-hybrid in linux, is there any command prompt to convert magnet url to .torrent file

**Comment by DiegoRBaquero** [comment]
There isn't, needs to be manually coded.
