### ISSUE TITLE
How to build / find appropriate WebRTC package

### ISSUE THREAD

**Issue by goatandsheep** [feross/webtorrent-hybrid#60]
I need a package that will automatically seed files from a node.js server without a screen over WebRTC to a front-end WebRTC client. I'm also willing to find / build a webRTC package that will work for that. The README claims to be waiting for [nickdesaulniers/node-rtc-peer-connection](nickdesaulniers/node-rtc-peer-connection) to be finished, which doesn't seem to be touched in over a year. What is the criteria you're looking for? Why was [wrtc](https://github.com/js-platform/node-webrtc) dropped

**Comment by feross** [comment]
`wrtc` was dropped because it segfaulted frequently and was difficult to install on many platforms (requiring a full download / compile of the chrome source, sometimes taking hours). I think the situation has improved since then, but we have already switched to `electron-webrtc`.

If you want to use `wrtc` instead, this package is pretty simple to change.
